name: Release Solver

on:
  push:
    tags:
      - 'v*'  # Триггер на теги

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y cmake g++

    - name: Build solver
      run: |
        mkdir -p build
        cd build
        cmake ..
        make
        ls -la

    - name: Create source archives
      run: |
        mkdir -p release
        tar -czvf release/solver-src.tar.gz --exclude='./build' --exclude='./.git' .
        zip -r release/solver-src.zip . -x 'build/*' '.git/*'

    - name: Generate packages (DEB, RPM)
      run: |
        cd build
        cpack
        mkdir -p ../release
        mv *.deb *.rpm *.tar.gz *.zip ../release/
        ls -la ../release

    - name: Upload release assets
      uses: softprops/action-gh-release@v1
      with:
        files: |
          build/solver
          release/*
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
